# Generated by Django 3.2.6 on 2021-10-01 00:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0002_alter_userfooditem_customer'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Costumer',
        ),
    ]
