# Generated by Django 3.2.6 on 2021-11-10 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0003_rename_customer_userfooditem_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditem',
            name='calories',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='carbohydrate',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='fat',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='protein',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=6),
        ),
    ]
